# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Acme-Marvel-CinematicUniverse-Characters`
	:runtime-requirement    [ :on "perl 5.008001"^^:CpanId ];
	:runtime-requirement    [ :on "Module::Pluggable"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
	:develop-requires       [ :on "Mite 0.005001"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.

